name: dartforcemvcexample
description: example of the dart force mvc framework
dependencies:
  forcemvc2:
    path: ../../ 
  http: any
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.11.0 <0.12.0'
dev_dependencies:
#  unittest: '>=0.11.0 <0.11.1'
  test: ^1.0.0
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
